[package]
name = "auto_enums_derive"
version = "0.5.10"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/auto_enums"
documentation = "https://docs.rs/auto_enums_derive/"
keywords = ["enum", "macros", "derive", "attribute"]
categories = ["rust-patterns"]
description = """
This library provides an attribute macro like a wrapper of `#[derive]`, implementing the supported traits and passing unsupported traits to `#[derive]`.
"""

[lib]
proc-macro = true

[dependencies]
derive_utils = { version = "0.9" }
lazy_static = "1.2"
proc-macro2 = "1.0"
quote = "1.0"
smallvec = "0.6.9"
syn = { version = "1.0", features = ["full"] }

[features]
# Default features.
default = ["std"]

# Enable to use `transpose*` methods.
transpose_methods = []

# ==============================================================================
# [std|core] libraries

# Enable to use `std` library's traits.
std = []

# Enable to use `[std|core]::fmt`'s traits other than `Debug`, `Display` and `Write`
fmt = []

# ==============================================================================
# external libraries

# futures(v0.3+)
futures = []

# futures(v0.1)
futures01 = []

# proc_macro, proc-macro2, quote, syn
proc_macro = []

# rayon
rayon = []

# serde
serde = []

# ==============================================================================
# Enable unstable features of [std|core] libraries.

# Implements `ExactSizeIterator::is_empty`.
exact_size_is_empty = []
# Implements `io::Read::read_initializer`.
read_initializer = []
# Make iterator implementation more effective.
try_trait = []

# ==============================================================================
# no-op (it is left to maintain compatibility)

# Implements `io::Read::read_vectored` and `io::Write::write_vectored`.
iovec = []
