[package]
name = "auto_enums_test_suite"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
publish = false

[dependencies]
futures = { version = "0.1", optional = true }
quote = { version = "0.6", optional = true }
rayon = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.6"

[dev-dependencies.auto_enums]
path = ".."
default-features = false
features = ["transpose_methods"]

[features]
default = ["external_libraries"]

type_analysis = ["auto_enums/type_analysis"]

std = ["auto_enums/std"]

external_libraries = [
    "std",
    "futures",
    "quote",
    "rayon",
    "serde",
    "auto_enums/futures01",
    "auto_enums/proc_macro",
    "auto_enums/rayon",
    "auto_enums/serde",
]

unstable = [
    "auto_enums/unstable",
    "auto_enums/read_initializer",
    "auto_enums/exact_size_is_empty",
    "auto_enums/try_trait",
    "auto_enums/unsized_locals",
]
